#!/bin/csh

#
# Install script for the load administration product (loadadmin)
#
# Usage:  Install
#
cd `dirname $0` && source ./Configuration

#
# Create a symbolic link to the configuration file in each sub-directory.
#
# NOTE: The adhoc directory is excluded because it has its own configuration
#       file and the adhoc load does not use mgiconfig.
#
foreach i (bin dev jboss prod)
    cd $i
    rm -f Configuration
    ln -s ../Configuration .
    cd ..
end

#
# Make sure the log directory exists.
#
if ( ! -d ${LOGSDIR} ) then
    mkdir -p ${LOGSDIR}
endif

#
# Set permissions.
#
chmod 754 Configuration Install

foreach i (bin dev jboss prod)
    chmod -fR 754 $i
    chgrp -fR progs $i
end

#
# Lock down permissions so only mgiadmin can use these scripts
#
chmod 700 bin/updateImsr*
