#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping Searchtool_pub2 JBoss Instance'
./stopSearchtool_pub2

sleep 10

echo 'Clearing jboss tmp files'
rm -R /usr/local/mgi/jboss/searchtool_pub2/tmp/work/*

echo 'Starting Searchtool_pub2 JBoss Instance'
./startSearchtool_pub2

echo 'Searchtool_pub2 Jboss Restarting - Check logs for completion.'
