#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping FEWI JBoss Instance'
./stopFewi

echo 'Clearing jboss tmp files'
rm -R /usr/local/mgi/jboss/searchtool_robot/tmp/work/*

echo 'Starting FEWI JBoss Instance'
./startSearchtool_robot

echo 'Fewi Jboss Restarting - Check logs for completion.'
