#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping Searchtool_prod JBoss Instance'
./stopSearchtool_prod

echo 'Clearing jboss tmp files'
rm -R /usr/local/mgi/jboss/searchtool_prod/tmp/work/*

echo 'Starting Searchtool_prod JBoss Instance'
./startSearchtool_prod

echo 'Searchtool_prod Jboss Restarting - Check logs for completion.'
