#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping StressTest JBoss Instance'

./stopSearchtool_stresstest

# Give the server time to shutdown gracefully.

sleep 15

echo 'Starting StressTest JBoss Instance'

./startSearchtool_stresstest

echo 'StressTest Jboss Restarting, check logs for completion.'
