#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping FEWI JBoss Instance'
./stopFewiBatch

sleep 10

echo 'Clearing jboss tmp files'
rm -R /usr/local/mgi/jboss/fewiBatch/tmp/work/*

echo 'Starting FEWI JBoss Instance'
./startFewiBatch

echo 'Fewi Jboss Restarting - Check logs for completion.'
