#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping FEWI JBoss Instance'
./stopFewi

echo 'Starting FEWI JBoss Instance'
./startFewi

echo 'Fewi Jboss Restarting - Check logs for completion.'
