#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping FEWI JBoss Instance'
./stopFewi

sleep 10

echo 'Clearing jboss tmp files'
rm -R /usr/local/mgi/jboss/fewi/tmp/work/*

echo 'Starting FEWI JBoss Instance'
./startFewi

echo 'Fewi Jboss Restarting - Check logs for completion.'
