#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping Searchtool_pub1 JBoss Instance'
./stopSearchtool_pub1

echo 'Clearing jboss tmp files'
rm -R /usr/local/mgi/jboss/searchtool_pub1/tmp/work/*

echo 'Starting Searchtool_pub1 JBoss Instance'
./startSearchtool_pub1

echo 'Searchtool_pub1 Jboss Restarting - Check logs for completion.'
