#!/bin/csh -f

cd `dirname $0` && source ./Configuration

echo 'Stopping Dev JBoss Instance'

./stopSearchtool_dev

# Give the server time to shutdown gracefully.

sleep 15

echo 'Starting dev JBoss Instance'

./startSearchtool_dev

echo 'Dev Jboss Restarting, check logs for completion.'
