#!/bin/csh -f

cd `dirname $0` && source ./Configuration

setenv MEM_MIN 4g
setenv MEM_MAX 4g

if (${?FEWI_MEM_MIN}) then
    setenv MEM_MIN ${FEWI_MEM_MIN}
endif
if (${?FEWI_MEM_MAX}) then
    setenv MEM_MAX ${FEWI_MEM_MAX}
endif

setenv SERVER_NAME `uname -n`
setenv JAVA_OPTS "-Xms${MEM_MIN} -Xmx${MEM_MAX} -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 "

# Remove any "failed" or "undeployed" files from the deployment directory.
# These files will cause the Fewi to not start up properly.
rm -f ${WILDFLY}/fewi/deployments/*.failed
rm -f ${WILDFLY}/fewi/deployments/*.undeployed

${WILDFLY}/bin/standalone.sh -b=${SERVER_NAME} -bmanagement=${SERVER_NAME} -Djboss.server.base.dir=${WILDFLY}/fewi &
