#!/bin/csh -f

cd `dirname $0` && source ./Configuration

setenv SERVER_NAME `uname -n`
setenv JAVA_OPTS "-d64 -Xms6g -Xmx6g" 

${JBOSS}/bin/standalone.sh -b=${SERVER_NAME} -Djboss.server.base.dir=${JBOSS}/searchtool_pub1 &
