#!/bin/csh -f

cd `dirname $0` && source ./Configuration

setenv MEM_MIN 4g
setenv MEM_MAX 4g

if (${?FEWI_MEM_MIN}) then
    setenv MEM_MIN ${FEWI_MEM_MIN}
endif
if (${?FEWI_MEM_MAX}) then
    setenv MEM_MAX ${FEWI_MEM_MAX}
endif

setenv SERVER_NAME `uname -n`
setenv JAVA_OPTS "-d64 -Xms${MEM_MIN} -Xmx${MEM_MAX} -XX:MaxPermSize=1g -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+UseConcMarkSweepGC -XX:+CMSPermGenSweepingEnabled -XX:+CMSClassUnloadingEnabled "

${WILDFLY}/bin/standalone.sh -b=${SERVER_NAME} -bmanagement=${SERVER_NAME} -Djboss.server.base.dir=${WILDFLY}/fewi &
