#!/bin/tcsh -f

cd `dirname $0` && source ./Configuration

setenv JAVA_HOME /usr/mgijava6
setenv JAVA ${JAVA_HOME}/bin/java
setenv SERVER_NAME `uname -n`

# Try to shutdown jboss gracefully.

${JBOSS}/bin/jboss-cli.sh --connect controller:${SERVER_NAME}:29999 :shutdown

