#!/bin/tcsh -f

cd `dirname $0` && source ./Configuration

# setenv JAVA_HOME /usr/mgijava6
# setenv JAVA ${JAVA_HOME}/bin/java
setenv SERVER_NAME `uname -n`

# Try to shutdown jboss gracefully.
${JBOSS}/bin/jboss-cli.sh --connect --controller=localhost:9999 :shutdown

# Give the shutdown time to finish.
sleep 10

# See if the process is still running. If so, kill it.
set PROCESS=`ps -aef | grep 'jboss/bin/standalone.sh' | grep 'fewi$' | awk '{print $2}'`
if ( "${PROCESS}" != "" ) then
    echo "Normal shutdown did not work. Kill process ${PROCESS}."
    kill -9 ${PROCESS}
endif
