#!/bin/tcsh -f

cd `dirname $0` && source ./Configuration

setenv SERVER_NAME `uname -n`

# Try to shutdown jboss gracefully.
${WILDFLY}/bin/jboss-cli.sh --connect --controller=${SERVER_NAME}.jax.org:9990 :shutdown

# Give the shutdown time to finish.
sleep 10

# See if the process is still running. If so, kill it.
set FEWI_PID=`ps -aef | grep 'wildfly/bin/standalone.sh' | grep 'fewi$' | awk '{print $2}'`
set FEWI_CHILD_PID=`ps -aef | grep 'Standalone' | grep " ${FEWI_PID} " | awk '{print $2}'`
if ( "${FEWI_PID}" != "" ) then
    echo "Normal shutdown did not work. Kill parent/child processes: ${FEWI_PID} ${FEWI_CHILD_PID}"
    kill -9 ${FEWI_PID} ${FEWI_CHILD_PID}
endif
